# Generated by Django 5.2 on 2025-04-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0002_toolcategory_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.tool')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.user')),
            ],
            options={
                'unique_together': {('user_id', 'tool_id')},
            },
        ),
    ]
