# Generated by Django 5.2 on 2025-04-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.user')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.subscriptionstatus')),
            ],
        ),
    ]
