# Generated by Django 5.2 on 2025-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0004_subscriptionstatus_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_key', models.CharField(max_length=100, unique=True)),
                ('param_value', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
