# Generated by Django 5.2 on 2025-04-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0005_systemparameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='tool_id',
            new_name='tool',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
